version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m
    SONAR_SCANNER_VERSION: "3.0.3.778"

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - run: sbt clean coverage test coverageReport scapegoat
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - persist_to_workspace:
          root: ~/
          paths: repo

  sonar-scan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - run:
          name: Set up sonar-scanner
          command: |
            echo "$SONAR_SCANNER_VERSION" > sonar-scanner-version
            wget -O sonar-scanner.zip "https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip"
            sudo unzip sonar-scanner.zip -d /opt
      - restore_cache:
          keys:
            - v1-sonar-cache-{{ checksum "sonar-scanner-version" }}
            - v1-sonar-cache-
      - run:
          name: sbt sonarScan
          command: |
            export SONAR_SCANNER_HOME="/opt/sonar-scanner-${SONAR_SCANNER_VERSION}"
            sbt -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONARQUBE_ACCESS_TOKEN} sonarScan
      - save_cache:
          key: v1-sonar-cache-{{ checksum "sonar-scanner-version" }}
          paths: ~/.sonar/cache

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "3c:1a:75:b1:62:85:3b:1b:61:94:f8:1f:8d:0e:1d:a1"
      - run:
          name: Set up git
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "mwz@users.noreply.github.com"
      - run:
          name: Set up sonar-scanner
          command: |
            echo "$SONAR_SCANNER_VERSION" > sonar-scanner-version
            wget -O sonar-scanner.zip "https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip"
            sudo unzip sonar-scanner.zip -d /opt
      - restore_cache:
          keys:
            - v1-sonar-cache-{{ checksum "sonar-scanner-version" }}
            - v1-sonar-cache-
      - run:
          name: sbt release
          command: |
            export SONAR_SCANNER_HOME="/opt/sonar-scanner-${SONAR_SCANNER_VERSION}"
            sbt -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.login=${SONARQUBE_ACCESS_TOKEN} 'release with-defaults skip-tests'
      - save_cache:
          key: v1-sonar-cache-{{ checksum "sonar-scanner-version" }}
          paths: ~/.sonar/cache

workflows:
  version: 2
  scala-sonar:
    jobs:
      - test
      - sonar-scan:
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - sonar-scan
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master
